/** Offline demo snapshot for regression / no-network */

export function demoSnapshot() {
  return {
    matchId: "demo-pitch-intel",
    eventId: "401842755",
    leagueId: "swe.1",
    league: "Swedish Allsvenskan",
    status: "pre",
    statusDetail: "Scheduled",
    clock: "0'",
    kickoff: "2026-07-19T14:30:00Z",
    venue: "Borås Arena",
    home: {
      id: "529",
      name: "IF Elfsborg",
      short: "ELFS",
      form: "LLDDD",
      record: "4-6-3",
      points: 18,
      rank: 9,
      goalsFor: 17,
      goalsAgainst: 14,
      gp: 13,
      gpg: 17 / 13,
      gapg: 14 / 13,
      homeAdv: 1.06,
      formAdj: -0.15,
      coach: { name: "Oscar Hiljemark", styleHint: "balanced" },
      players: [
        { name: "Leo Ostman", goals: 4, apps: 13 },
        { name: "Ari Sigurpalsson", goals: 3, apps: 11 },
        { name: "Arber Zeneli", goals: 3, apps: 10 },
      ],
    },
    away: {
      id: "8547",
      name: "IK Sirius",
      short: "SIR",
      form: "WDWWW",
      record: "10-2-0",
      points: 32,
      rank: 1,
      goalsFor: 33,
      goalsAgainst: 15,
      gp: 12,
      gpg: 33 / 12,
      gapg: 15 / 12,
      awayDamp: 0.97,
      formAdj: 0.12,
      coach: { name: "Christer Mattiasson", styleHint: "direct" },
      players: [
        { name: "Robbie Ure", goals: 12, apps: 12 },
        { name: "Isak Bjerkebo", goals: 10, apps: 12 },
        { name: "Marcus Lindberg", goals: 1, apps: 12 },
      ],
    },
    score: { home: 0, away: 0 },
    odds: { provider: "demo", home: 3.45, draw: 3.7, away: 1.74 },
    lineupsConfirmed: false,
    source: {
      name: "demo-snapshot",
      fetchedAt: new Date().toISOString(),
      latencyMs: 0,
      reliability: "low",
    },
    notes: ["Demo snapshot; live mode uses ESPN"],
    offline: true,
  };
}
